---
title: "NPS Project Overview"
author: "Charles maintains this page; feel free to add."
date: "Updated: `r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objective

> What are the key drivers of NPS?

What can we learn from data that has already been collected? 

We want to aggregate the data associated with NPS that has been collected across NAB in different projects and build some exploratory models to understand key (and actionable) features.

## Bringing it all together

> What do we need to aggregate?

- Roy Morgan's survey data: demographics, various measures. Most importantly, we will calculate the target measure **NPS** from these data.
- Jordan Thomas and Tian Li have done a great deal of work using an NLP (Natural Language Processing) machine on text and sentiment analysis. These data are customer-identified, so we can join their data to ours on a customer level. 
- Shepit is working on an algorithm to help us with identifying feature clusters associated with promoters and detractors. 

## Current blockers 

- Extracting the data from Roy Morgan's database. We will be able to progress this further at the training session next week. 
- Shepit, Charles, and Paul are still working on the rollout of a GitHub-integrated analytics workflow.

## Action items

- Charles to set up a repository for this (where subprojects will be tracked in future).
- Charles to port across this documentation to the repo.

## Key people 

Name|Affiliation|Role in this project
-|-|-
Nick|PwC|Project lead
Wayne|NAB|Project contact at NAB
Matt|PwC|Analyst, expert in control theory model
Charles|PwC|Analyst and data monkey
Jordan|NAB|Has performed NLP analysis on NPS data
Erin|NAB|Liaison with Roy Morgan
Ibrahim|Roy Morgan|Asteroid training

## Meeting notes

### 18 January 2018

- With Barry, Thomas, 
- Nick provided an update 
  - met with Jordan Thomas
  - 70 observations per month; small sample --> lots of noise
  - Reasons for satisfaction - explore the correlation with NPS.
  - Main resource right now is the survey.
- Strategic NPS
  - Machine learning question: manual category analysis, explore bias in wording. 
  - Advanced analytic techniques: NLP. 
  - Analyse looking for a relationship between strategic NPS and ?
  - Look at difference between detractors and promoters.
  - You remember the big things and the most recent interaction. 
  - Look at fixing bad things, and also reminding customers of good things. So, find things that everyone (or at least promoters and passives) says is good. 
- Hypotheses
- Interested in changes over time 
- Hoping to see some spikes - let's do some explantory analysis on this. 
- Infer a different NPS score based on customer attrition. 
- Call centre.  

## Glossary

Term|Description
-|-
NPS|Net Promoter Score
Asteroid|Roy Morgan's database
