---
title: "todos for blogplost"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Hi Charles. I'll make a few comments here that I hope will be helpful & I'll leave troubleshooting your hugo serve till last-ish 'cause that's not my forté

- [NA] I will add the `topicid` just before your post is published. Will have no influence on the preview. `topicd` comes from us adding a link to your post in our discussion forum and this allows comments in the blog to be posted automatically to the forum 
- [Done] I think you should omit `package_version` in YAML because while you're referring to `weathercan`, it's not *about* the package itself
- [Done] can you spell out OOF in parentheses after the acronym? Curiosity stopped me from reading to make me think about it and that detracted from the flow
- [Good point! Done] in "...console testing we all do when writing functions..." maybe best to omit "all" - maybe some readers are even more beginner than that? (it me)
- [Done] "Up until now my until now, ..." omit repeated words
- [Needs a readover when I can compile] "The tests sounded like this." Would you consider prefacing  this with "To me, "? I LOVE the analogy. On first read, it made me stop and think again too much, and someone not knowing your background might even stall longer.
- [Done] In "Writing functions with documentation and tests felt like this." do you mean writing them at same time / integrated, as you refer to above? If yes, please clarify a bit so the analogy to progression of the music samples is crystal clear
- can you send a screenshot of what you see when you do `hugo serve`?
